/*
 * Copyright 2020 Google LLC
 *
 * Use of this source code is governed by an MIT-style
 * license that can be found in the LICENSE file or at
 * https://opensource.org/licenses/MIT.
 */

package com.fdahpstudydesigner.controller;

import static com.fdahpstudydesigner.common.StudyBuilderAuditEvent.USER_SIGNOUT_SUCCEEDED;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultHandlers.print;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.view;

import com.fdahpstudydesigner.common.BaseMockIT;
import com.fdahpstudydesigner.common.PathMappingUri;
import org.junit.Test;
import org.springframework.http.HttpHeaders;

public class LoginControllerTest extends BaseMockIT {

  @Test
  public void shouldLogoutSuccessfully() throws Exception {
    HttpHeaders headers = getCommonHeaders();
    mockMvc
        .perform(
            get(PathMappingUri.SESSION_OUT.getPath())
                .headers(headers)
                .sessionAttrs(getSessionAttributes()))
        .andDo(print())
        .andExpect(status().isFound())
        .andExpect(view().name("redirect:login.do"));

    verifyAuditEventCall(USER_SIGNOUT_SUCCEEDED);
  }

  @Test
  public void shouldThrowBadRequestException() throws Exception {
    HttpHeaders headers = getCommonHeaders();
    headers.set("source", "INVALID STUDY BUILDER");
    try {
      mockMvc
          .perform(
              get(PathMappingUri.SESSION_OUT.getPath())
                  .headers(headers)
                  .sessionAttrs(getSessionAttributes()))
          .andDo(print())
          .andExpect(status().isFound())
          .andExpect(view().name("redirect:login.do"));
      fail(
          "shouldThrowBadRequestException() didn't throw BadRequestException when I expected it to");
    } catch (Exception e) {
      assertTrue(e.getMessage().contains("Invalid 'source' value"));
    }
  }
}
